### PR TITLE
Update fork2

### PR DESCRIPTION
**Pull request by JonasVautherin**

### CODE REVIEW

**Comment by JonasVautherin** [comment]
@TSC21: would be nice if you could have a look, I could use your help to fix the remaining CI tests :+1:.

I will need an up-to-date MAVSDK soon in AuterionOS

**Comment by JonasVautherin** [comment]
@TSC21 Actually more changes are coming in MAVSDK upstream (which should help with MAVLink dialects), so maybe you'd rather try to merge upstream again (like after https://github.com/mavlink/MAVSDK/pull/1733 is merged)?

**Comment by TSC21** [comment]
@JonasVautherin please do and I will review again. Only point to understand after is if the custom action waypoints in the Autopilot Manager continue to work. I can test that with SITL

**Comment by TSC21** [comment]
Btw I have no idea why the SITL tests with upstream and why the Windows build is failing.

**Comment by JonasVautherin** [comment]
Well that's outdated, I don't see the point of putting more work into this branch, as it should rather be done against MAVSDK upstream.

On my end, my project is using MAVSDK upstream, so I don't need this anyway.

**Pull request closed without merging**
